### ISSUE TITLE
implement mouse.isPressedIn(shape)

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#104]
The PsychoPy lib supports 
`mouse.isPressedIn(stim)` 
returning a bool. This was always just a shorthand for
`sum(mouse.buttons())>0 and stim.contains(mouse)`
and although I personally considered it unecessary it is reasonably widely used so seems sensible to implement. 

You can see the Python implementation at 
https://github.com/psychopy/psychopy/blob/7ea4a9e81c585eb4e57b919837fe8268b4144345/psychopy/event.py#L856

**Comment by peircej** [comment]
@thewhodidthis this might be one for you (sorry I can't "assign" to you yet because I haven't set you up on the project)

**Comment by thewhodidthis** [comment]
@peircej On it
