### ISSUE TITLE
names of keys

### ISSUE THREAD

**Issue by JensBoelte** [psychopy/psychojs#106]
Hello, I am programing an anchoring experiment and I have manage to register all revelvant keys (0-9) as a response. However, online I can't register three keys, the - (minus) on the keyboard, the subtract-key on the num-pad and the enter-key on the num-pad. I assume that I am using the wrong keycode oder keyname to register them. I searched to keynames in Python and JavaScript but the ones I found did not work, e.g. _NumpadSubtract, minus, numpad_enter_. I need the minus-sign to allow for negative numbers, e.e.g temperature. Any suggestions Jens

**Comment by JensBoelte** [comment]
Hello, I found the problem. Using a German keyboard gives a _slash_ instead of a _minus_ or - online. Also, it is _num_subtract_ not _NumpadSubtract_ as I found in a list of keynames. _numpad_enter_ did not work because of an error in the if-construction.

**Comment by peircej** [comment]
For completeness of the info, is this solved or did it turn out not to be an issue?

**Comment by JensBoelte** [comment]
The problem has been resolved. I was just surprised to find out that on a German keyboard-layout a minus has the keycode slash.
