### ISSUE TITLE
Avoid recreating Pixi objects on every update

### ISSUE THREAD

**Issue by thewhodidthis** [psychopy/psychojs#114]
Take the ImageStim for instance. calling `.setPos()` triggers an update vis the `_needUpdate` attribute which makes sense but as part of that update is reloading the image with
```javascript
		this._texture = new PIXI.Texture(new PIXI.BaseTexture(this._image));
		//this._texture = new PIXI.Texture(PIXI.BaseTexture.fromImage(this._image));
		this._pixi = new PIXI.Sprite(this._texture);
```

What I'm arguing for is that the code above is performed just once as part of the `setImage` call. The update calls should onlye be changing the pos, ori, etc. @apitiot is there a reason that this isn't possible? I feel sure that calls like `new PIXI.Texture(new PIXI.BaseTexture(this._image))` are doing a fair bit of work and should be called as rarely is possible

_Originally posted by @peircej in https://github.com/psychopy/psychojs/pull/110#issuecomment-663622160_

**Comment by peircej** [comment]
https://github.com/psychopy/psychojs/pull/110#issuecomment-664150728

Great

For naming maybe `_needsUpdate` updates more widely and `_needsVertexUpdate` is the more specific version that doesn't update the texture? Or maybe we ditch `_needsUpdate` altogether on the basis that it isn't specific enough? Just thoughts. Whatever works for you guys! :-)
