### ISSUE TITLE
make psychojs an "independent" project with its own releases?

### ISSUE THREAD

**Issue by yarikoptic** [psychopy/psychojs#12]
Now that it was extracted from psychopy code body into a submodule I think it would make sense  to make dedicated psychojs "project" and have releases etc

**Comment by peircej** [comment]
Fair point. Potentially we'll just make releases to coincide with PsychoPy releases though, and possibly with the same version number. I don't know much about how this works in JS land and I'm not going to make any substantial decisions/changes until we hear back from Wellcome Trust about funding for completing the dev on this.
