### ISSUE TITLE
Orientation of polygons& bitmaps in PsychoJS is the opposite of their orientation in PsychoPy

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#120]
I defined a couple of polygons and images in PsychoPy builder that had an orientation of 5 degrees. In the builder, the polygons are rotated to the right, but online they are rotated to the left. 

*** Polygons
GitLab: https://gitlab.pavlovia.org/tpronk/e2e_polygons
Pavlovia runner: https://run.pavlovia.org/tpronk/e2e_polygons/html/

*** Bitmaps
GitLab: https://gitlab.pavlovia.org/tpronk/e2e_img
Pavlovia runner: https://run.pavlovia.org/tpronk/e2e_img/html/

**Comment by thewhodidthis** [comment]
@tpronk Is this different to #87 for which a PR has been already drafted? Feel free to reopen if so.
