### ISSUE TITLE
A loop of loopType fullRandom seems to draw without replacement

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#123]
This concerns a similar issue as I found in PsychoPy. See the description of the issue over here: https://github.com/psychopy/psychopy/issues/2988

In this case, I suspect the misbehaving code could be over here: https://github.com/psychopy/psychojs/blob/08972dae9087622b0d18b68ef89c9ccd8a92e80d/js/data/TrialHandler.js#L571

**Comment by peircej** [comment]
I think this is a misunderstanding of what fullRandom is supposed to do but do check
