### ISSUE TITLE
Different behavior isPressedIn between PsychoPy and PsychoJS

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#136]
I build an experiment in which different polygon stimuli light up when you click then:
- https://gitlab.pavlovia.org/tpronk/e2e_buttons
- https://run.pavlovia.org/tpronk/e2e_buttons/html/

In PsychoPy, the shape only lights up when I click inside of it. In PsychoJS, the shape lights up when I click inside of its bounding box. For example: clicking slightly to the top-right of the center of the cross (but outside of the cross itself), PsychoPy does not light up, but PsychoJS does.

**Comment by apitiot** [comment]
Well spotted!
This temporary regression has just been solved. The example is now working as expected.
I'm closing the issue.
