### ISSUE TITLE
Running Psychopy on lab server

### ISSUE THREAD

**Issue by adamjbarnas** [psychopy/psychojs#138]
Hello - I am trying to run psychopy on my lab's server. I've seen some previous posts that said this was not possible at the time, but I am wondering if progress has been made on this front. The experiment runs fine locally. I've generated the necessary index and javascript files and loaded the corresponding libraries, but I am getting the following error whenever I try running the experiment: 

<img width="517" alt="error" src="https://user-images.githubusercontent.com/61851424/89566641-1a2f9f80-d7e6-11ea-86a2-84b93139b921.png">

Can you please help me work through the error? I am happy to share additional info and the experiment link if it is necessary.

**Comment by thewhodidthis** [comment]
Hey @adamjbarnas,

This is probably lack of documentation on our part, thanks for flagging, sorry I was unable to respond sooner. On Pavlovia, media and other external resources all live in a set directory, so the script knows where to find them for downloading when the experiment first boots up.

When running studies locally, it is necessary to tell PsychoJS where any such resources are located. You can do that by including a `resources` array as part of the options you give the `psychoJS.start()` call. With reference to [the manual section on downloading resources](https://pavlovia.org/docs/experiments/resources), tweaking your script along the following lines should work:

```js
psychoJS.start({
  expName: expName,
  expInfo: expInfo,
  resources: [
    {
      // Shorthand for referencing the file in your script
      name: 'matching_prompt',
      // Where the file is located relative to your 'index.html'
      path: 'matching_prompt.png'
    },
  ]
});
```

Please feel free to follow up if that fails to solve the problem. We also have a [dedicated user support forum](https://discourse.psychopy.org) to provide help with taking PsychoPy experiments online.

**Comment by peircej** [comment]
Just to add to @thewhodidthis's comment that collecting data on your own server still isn't something we currently formally support
