### ISSUE TITLE
Sounds not supporting files yet?

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#16]
Last I knew (i.e. back in July) sounds only supported tones, but sound files were "imminent". Has that changed?

**Comment by apitiot** [comment]
It has indeed. The Sound stimulus can play a variety of sound files. At the moment, they are loaded together with the other resources, which might take some time, should they be big. We need to discuss the scheduling of the loading of resources in general.

I have a couple of questions:

- Is stop an actual stop, i.e. it is not a pause? If so, perhaps we also want a pause?
- What does autostop do?

**Comment by peircej** [comment]
Not sure what "autostop" is about. Ignore it. So I guess we can close this one
