### ISSUE TITLE
Pavlovia needs data-submit API so that lab.js and jsPsych can use it

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#17]

**Comment by apitiot** [comment]
jsPsych is very straight-forward. A tentative approach would be:

```javascript
[...]
/* start the experiment */
pavloviaSession = jsPsych.openPavloviaSession(psychoJsManagerUrl, experimentFullPath);
jsPsych.init({
  timeline: timeline,
  on_finish: function(data) {
    jsPsych.uploadDataToPavlovia(pavloviaSession, data);
  }
});
[...]
```

The code of submitToPavlovia would be very similar to ServerManager.uploadData, which I can easily adapt and share with the jsPsych team.

How does that sound?

**Comment by apitiot** [comment]
This feature was added some time ago, in the form of lab.js and jsPsych plugins.
I'm closing the issue.

**Comment by munoztd0** [comment]
Hello,

So is there a similar fix for lab.js now since this issue is closed?
