### ISSUE TITLE
textbox issues

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#182]
I encountered some issues with the PsychoJS implementation of textbox. 

This is the example experiment:
- https://run.pavlovia.org/tpronk/e2e_textbox/html/
- https://gitlab.pavlovia.org/tpronk/e2e_textbox

These are the issues I encountered:
1. I type something into the textbox and then continue to the next procedure. Calling textbox.getText() via PsychoPy returns the text I just typed in, but via PsychoJS it returns the initial value of the textbox.
2. If I change the width and height of the textbox via the PsychoPy builder (for example to 1, 1 height units), then PsychoPy changes the size of the textbox accordingly. PsychoJS only changes the width, but not the height.
3. The procedure after the textbox can be finished via a mouse click. In PsychoPy the first click is registered, but in PsychoJS, I need to click twice.
4. I tried the experiment on my Xperia 10-II, Firefox, Chrome, and Edge.
  - On Firefox, the keyboard pops up when I focus the textbox by tapping it.
  - On Chrome and Edge, after I focus the textbox, the keyboard briefly pops up, but then disappears again

**Comment by tpronk** [comment]
BTW, I also noticed that setting the height and width properties does affect the size of the textbox in PsychoPy, but not in PsychoJS

**Comment by peircej** [comment]
My guess is that (2) is an issue with the code we generate from Builder (i.e. it's a PsychoPy issue not PsychoJS problem). The other 2 look like PsychoJS issues

**Comment by tpronk** [comment]
Follow-up:

About (2). I do think it's in PsychoJS and not the builder. Here are my arguments:
- In the generated JS, the constructor of the textbox receives a property `size: [1, 1]`
- I made a adjustment to the experiment so that textbox is exposed to the Browser console. If I use the console to change the size of the textbox via `textbox.setSize([1, 1])`, I do see the width change, but not the height. 
- I did notice the issue is only with height, not widt; I updated the original issue to reflect this

I added a (4) about an issue I noticed on mobile browsers

**Comment by tpronk** [comment]
@thewhodidthis's #191 also refers to my issue (2)

**Comment by thewhodidthis** [comment]
@tpronk I understand these items are all TextBox related, but because they likely have separate causes and potential solutions, would it be possible to have them raised as individual issues?

**Comment by tpronk** [comment]
Will do @thewhodidthis

**Comment by tpronk** [comment]
Made new issues for each item that wasn't yet raised by @thewhodidthis, closing this issue.
