### ISSUE TITLE
slider with default settings does not show the circle that serves as cursor

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#183]
Via the builder, I made a slider with default settings. The slider itself looks very similar between PsychoPy and PsychoJS, but the cursor is different: in PsychoPy, upon clicking and dragging the mouse on the slider, I get a circle that moves along with the pointer's x-location. On PsychoJS, I don't get this cursor. 

- https://gitlab.pavlovia.org/tpronk/e2e_slider
- https://run.pavlovia.org/tpronk/e2e_slider

NB, after the slider, the experiment continues with e2e-calibration procedure. I left that in, so I can easily adjusted this experiment later on for an automated e2e-test of the slider

**Comment by thewhodidthis** [comment]
@tpronk PsychoJS like PsychoPy renders no marker by default. I believe the problem here is that contrary to PsychoPy dragging in PsychoJS is available on the marker alone, which is hidden and seated mid-range on load. Closing in favour of #195

**Comment by tpronk** [comment]
Check :)
