### ISSUE TITLE
Need to implement a callOnFlip() func/schedule for better RT precision

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#19]
Response times should be measured from when the stimulus actually appears, not when it is requested. To do that we need to reset the RT clock when screen flip occurs. Most general way to do that (in keeping with psychopy) is with a `Window.callOnFlip()` function. Operates a bit like the scheduler calls: first arg is the function, and further args to be passed to the function if needed. 

We need code to detect the win flip and run the list of function calls then. That's the tricky bit, but seems possible using opengl trick with a flush() call. I think I sent a link on how to do that in an email a few months ago, but can't now find the details again. I'll go back to google and re-link here

**Comment by peircej** [comment]
This link is where I saw the info on what should work:
http://www.html5gamedevs.com/topic/27849-detect-when-view-has-been-rendered/

Basically, we should call `requestAnimationFrame` and probably also
```
renderer.gl.readPixels(0, 0, 1, 1, renderer.gl.RGBA, renderer.gl.UNSIGNED_BYTE, new Uint8Array(4));
```
In my experience of this on native opengl calls, the call to swap buffers (`requestAnimationFrame` in JS?) is designed to wait only if it doesn't have a spare buffer to draw to. So it would give us sync correctly, but it doesn't necessarily block until the flip occurs because there might be a second buffer ready. The call to readPixels ensures that the flip has already occurred. i.e. the difference between sync to VBL and block on VBL is subtle but important, and my guess is that `requestAnimationFrame` will only give us sync.

**Comment by apitiot** [comment]
We have been using requestAnimationFrame from the get-go. I have added a call to renderer.gl.readPixels in Window.render() to be extra-sure, but, as far as I can ascertain, it is not necessary, since PIXI's renderer.render() won't return until the GPU has rendered the scene. I am not equipped to check whether that it is true, however. That might be a job for David.

callOnFlip is now available. It can be called very simply:

```javascript
[...]
psychoJS.window.callOnFlip(flipCallback, 1,2,3);
[...]

function flipCallback(a,b,c) {
  console.log('on window flip: ', a,b,c);
}
```

**Comment by peircej** [comment]
Sounds good. Yes @dvbridges can then check whether the call makes a difference to timing precision.

"won't return until the GPU has rendered the scene" That statement is true in C OpenGL contexts too, but it isn't quite enough and read/write pixels still helps. I can't explain it easily by text so I'll try and explain verbally (with associated hand movements and/or drawings) next week! ;-)

**Comment by peircej** [comment]
I was just looking at this in the code at https://github.com/psychopy/psychojs/blob/965814fa905bd7362829772c35a50b5afd552175/js/core/Window.js#L172 
and it looks like this is written as a single callback function. 

The PsychoPy implementation actually stores a list of functions all to be executed, each only once. Each time `win.callOnFlip()` is called a function is added to the list of things that needs calling. After it gets called it gets popped from the list. This allow users to set multiple things to occur on a single flip without needing to track what else was being done. (e.g. reset a clock, send a trigger, and also send a log entry). Could the PsychoJS implementation be updated to match?

**Comment by apitiot** [comment]
Fixed :-)
