### ISSUE TITLE
PsychoJS.window.monitorFramePeriod assumes 60 Hz; suggestions for adapting requested duration to arbitrary refresh rates

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#199]
I built a demo experiment in which I compare a custom-built measurement of the duration between screen refreshes with PsychoJS.window.monitorFramePeriod. I tested both measurements by setting my screen to 144 Hz (6.94... ms per refresh) and seeing what got reported. My custom-built measurement was quite accurate (reporting 7.02 ms per refresh), but PsychoJS.window.monitorFramePeriod reported 16.6... ms per refresh. Since PsychoJS times the moment for requesting a stimulus offset based on PsychoJS.window.monitorFramePeriod, this could result in stimuli being presented slightly too briefly when refresh rates are particularly high. 

Here are two suggestions for solutions. 
1. Don't bother with trying to adjust for durations between refreshes, but consider the first call to "each frame" of a routine as t =0. If requests for stimulus onset and stimulus offset are both timed relative to this t = 0, and actual drawing operations in both cases are delayed until the next refresh, then their duration is kept nicely constant. This has the added benefit that stimuli that should be presented immediately after eachother will not have any empty frames in between. 
2. Log timestamps of stimulus onset and offset in the requestAnimationFrame callback to get an idea of actual presentation time
3. Use an algorithm similar to my demo experiment to estimate durations between refreshes.

Demo experiment:
- https://pavlovia.org/run/tpronk/demo_refresh_rate/
- https://gitlab.pavlovia.org/tpronk/demo_refresh_rate

**Comment by peircej** [comment]
Yes, indeed. And we should be recording/reporting the actual monitorFramePeriod too (in the Python code we do that).

**Comment by tpronk** [comment]
Confirmed. I'll play around a bit to find out if I can move towards more concrete implementation suggestions
