### ISSUE TITLE
Windows 10 + Edge: issue with dialog box on window resize

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#209]
On Windows 10 + Edge, the contents of the dialog box can overflow its container (see [screenshot](https://ibb.co/tHGF7hH)) if I do the following:

1. I start an experiment with a maximized window
2. I resize the window to a width of less the 980px

**Comment by thewhodidthis** [comment]
@tpronk This happens cross browser because styling for mobile takes over increasing base font size, but only some elements are tied to it for relative sizing
