### ISSUE TITLE
Pavlovia 'activate' link needs more options and better visuals

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#21]
- [x] A user might want to prevent further data collection. So we need to be able to deactivate.
- [x] The current representation doesn't exactly leap out to a novice that it's controlling participant recruitment. In the original discussions we had the label was about recruiting or not and we'd talked about setting how that recruitment
- [x] When the user chooses to activate/recruit we should be providing them with options of how the data will be saved (SQL or flat CSV etc) and how recruitment will work (do we need to generate a set of participant IDs and send emails?)

**Comment by apitiot** [comment]
The recent, complete rework of the Pavlovia back-end and GUI now gives much more information about the various experiment status and enable fine control over how the data is saved. It also specifically highlight the link between a RUNNING experiment and recruitment. At the moment, the only recruitment strategy is URL.

I'm closing this issue and will open a new one about adding more recruitment strategies.
