### ISSUE TITLE
Windows 10 + Firefox: scrollbars can appear when resizing window

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#210]
This does not happen consistently; sometimes they appear and sometimes they disappear again. I have also noticed the following:
- The overflow is roughly the size of the scrollbars
- When I launch an experiment where I set "overflow = hidden" on the HTML root node, the issue does not occur.

Hence I suspect it's due to a race condition between the window and the PsychoJS resizing algorithm.

**Comment by thewhodidthis** [comment]
@tpronk This happens cross browser because styling for mobile takes over increasing base font size, but only some elements are tied to it for relative sizing
