### ISSUE TITLE
Mouse response in routine after textbox requires two clicks

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#214]
I built an demo experiment with the following procedure: first a routine with a textbox, then a routine that finishes after a mouse click In PsychoPy the first click is registered, but in PsychoJS, I need to click twice. Confirmed in Windows 10 + Firefox, Chrome, and Edge.

Demo experiment:
* https://run.pavlovia.org/tpronk/e2e_textbox/html/
* https://gitlab.pavlovia.org/tpronk/e2e_textbox

**Comment by peircej** [comment]
I think I had something similar with clicking on a button. I wasn't sure if it was that I need to activate the browser window with the first click, but I'm not sure that was it. Maybe the _canvas_ needs activating?

**Comment by tpronk** [comment]
I don't think so (but I'm not 100% sure). To focus the textbox in the first routine, I already need to click inside of it.

**Comment by thewhodidthis** [comment]
@tpronk Do you mean that you need to click twice inside the TextBox in order to be able to type in it?

**Comment by tpronk** [comment]
No, it's about the routine after the textbox that registers the mouse click.

**Comment by tpronk** [comment]
I've updated the e2e test at the top of this thread. Taking part in this experiment now consists of the following steps:

1. Click past the intro screen
2. Click in the textbox
3. Type something in the textbox
4. Click the blue square
5. Next, you'll see the text your just typed in
6. Click again to finish the experiment

There still seems to be a little issue with two clicks being required. On Win 10 FF/Chrome, step 4, I need to click the blue square twice to continue to the next routine. I also tried out some other scenarios, with the following findings:
* In step 4, it doesn't matter where the first click is, so long as the second click is on the blue square
* If I skep step 3 (don't type anything), I still need to click twice
* If I skip step 2&3, the first click on the blue square makes me continue to the next routine
* If I execute step 2&3, next click once anywhere, and then repeat step 2&3, I only need to click once on the blue square to continue

**Comment by thewhodidthis** [comment]
Closing in favour of #237
