### ISSUE TITLE
visual/TextInput: missing check for hasOwnProperty causes error

### ISSUE THREAD

**Issue by elatsoshvili** [psychopy/psychojs#253]
https://github.com/psychopy/psychojs/blob/ea83f8c307a28ff15af4ec3dfdda8694a14b7df0/js/visual/TextInput.js#L677

The loop that goes through `states` goes beyond the actual items and Array functions are passed to the `_box_generator` function, causing errors later and halting execution.
The loop should have a check using `hasOwnProperty`

**Comment by elatsoshvili** [comment]
I guess this problem only occurs after Array is extended according to the ["PsychoPy Python to Javascript crib sheet"](https://docs.google.com/document/d/13jp0QAqQeFlYSjeZS0fDInvgaDzBXjGQNe4VNKbbNHQ/edit) and some functions are added to the Array.prototype.

**Comment by thewhodidthis** [comment]
Well spotted @elatsoshvili, thanks for flagging
