### ISSUE TITLE
BUG: linebreak in fstring causes linebreak in JS code

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychojs#259]
Using an fstring in a textstim e.g. 

$f"I would like a \n line break here"

Will result in a linebreak in the exported .js code.

**Comment by thewhodidthis** [comment]
@RebeccaHirst Thanks for flagging, this looks like a JS code generation issue and therefore PsychoPy related. Could you raise with them please? If it turns out that there are extra tweaks required on the PsychoJS side as well, I will be sure to pick up no problem!

**Comment by RebeccaHirst** [comment]
Sure I have now flagged https://github.com/psychopy/psychopy/issues/3476
