### ISSUE TITLE
continueRoutine support

### ISSUE THREAD

**Issue by danielsnider** [psychopy/psychojs#27]
Is it true that `continueRoutine` doesn't work in PsychoJS? I've been trying to write a conditional loop like in [psychopy](https://discourse.psychopy.org/t/conditional-looping/1367) using `continueRoutine` but it doesn't work. Just knowing that it doesn't work now is helpful. A fix is even better.

**Comment by peircej** [comment]
"it doesn't work" ?
Error message? Syntax error? Page doesn't load? No error but routine continues? Could you point us to a link to test it?

**Comment by peircej** [comment]
If you look at the stroop example code
  https://gitlab.pavlovia.org/demos/stroop/blob/master/html/stroop.js
you'll see it pops up quite a bit, so my *guess* is that it does work.

**Comment by apitiot** [comment]
As far as I can tell, it is working fine. I'm closing the issue.
