### ISSUE TITLE
BUG: cannot set independant opacity for multiple polygons 

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychojs#275]
You currently cannot manipulate the opacity of multiple polygons in the same routine online.

In this Demo I either want to present 1, 2 or 0 polygons, and instead 1 is always presented. 

https://gitlab.pavlovia.org/lpxrh6/testopacity

**Comment by tpronk** [comment]
Made a slightly modified version of Becca's test. This one presents each of the polygons for an infinite duration. I noticed the polygons do show up after you resize the window.

https://run.pavlovia.org/tpronk/e2e_polygon_opacity/

**Comment by thewhodidthis** [comment]
@tpronk @RebeccaHirst Support fork using #203 as potential fix [run.pavlovia.org/support/testopacity &rarr;](https://run.pavlovia.org/support/testopacity/)
