### ISSUE TITLE
csv files need to watch out for commas and newlines within cells

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#28]
If a cell contains either a comma (e.g. a coordinate, an array or list) or a newline (a multi-line piece of text) then that cell needs to be written inside quotes. Note that newline chars could also differ according to the user's OS of course.

For example of new-line problems: https://discourse.psychopy.org/t/online-experiment-saved-data-was-format-misplacement/5986

**Comment by apitiot** [comment]
I believe this is now correctly handled.
