### ISSUE TITLE
textbox not editable

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychojs#295]
Textbox is not editable online in version 2021.2
. See here for minimal demo https://gitlab.pavlovia.org/lpxrh6/textbox2021-test/tree/master 

Originally reported here https://discourse.psychopy.org/t/typed-text-in-text-box-doesnt-appear-in-pavlovia/21799/2

**Comment by tpronk** [comment]
I'm going to assume this issue is resolved.
