### ISSUE TITLE
Empty trials being added to trial handler

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#30]
Two examples of empty trials being added to the trial handler, probably related to the condition files formatting.

*Example 1*
https://pavlovia.org/run/dvbridges/dpbe_l2/html/
*Example 2*
https://pavlovia.org/run/FrankBartel/epp3-keyboard/html/

*Slightly different example with what may be errors in filenaming - filenames starting with numbers do not work - perhaps we can warn users in PsychoPy as well*
https://pavlovia.org/run/jvcasillas/dpbe_l2/html/ 

**To fix this issue, users are currently required to:**
- Create a new conditions file
- Copy only the cells with information from the old conditions file, to the new conditions file
- *Avoid copying whole columns*, as this will also copy the empty formatted cells.
- Save new conditions file, and delete the old, error-causing conditions file.

**Comment by dvbridges** [comment]
A recurring problem, for example, see the trial handler from a recent Discourse post:

![blankTrials](https://user-images.githubusercontent.com/22459095/54120553-e7fef000-43ef-11e9-920a-2b39b7c4a315.png)

**Comment by apitiot** [comment]
As far as I can ascertain, this has to do with the XLSX library incorrectly reading some .csv files and inserting blank rows. I have added an option to not include blank rows, which seems to have done the trick.

The fix is available from version 3.0.1 onwards.
I am closing the issue.
