### ISSUE TITLE
Infinite duration for Sound component not infinite

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#31]
Leaving the sound duration empty in the Sound component gives a sound component parameter of ```secs: -1``` e.g.,

```
sound = new Sound({
    win: psychoJS.window,
    value: 'A',
    secs: -1,
    });
```
In PsychoPy, ```secs: -1``` should give an infinite duration tone, but online only a brief sound is played.

**Comment by apitiot** [comment]
This feature had indeed not been implemented just yet.

It is availabe now, as of the future 3.2.0.
