### ISSUE TITLE
Response data as list not being saved on each trial

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#32]
When saving data using ```psychoJS.experiment.addData```, list data is not being saved. For example, saving "all keys" for the keyboard, or mouse state on every frame, saves no data for that response device.

*Example including a single data file, where keyboard responses are missing for all keys pressed*
https://gitlab.pavlovia.org/dvbridges/mousetesting
https://pavlovia.org/run/dvbridges/mousetesting/html/

**Comment by apitiot** [comment]
This had to do with the XLSX library not knowing what to do with array values, which is perfectly reasonable since the .xlsx format is not designed to handle cells as arrays.
I am now converting arrays into their JSON string equivalent. The fix is available in 3.0.5.
Running dvbridges/mousetesting now gives, as a typical output:

> mouse.x,mouse.y,mouse.leftButton,mouse.midButton,mouse.rightButton,mouse.time,key_resp_2.keys,key_resp_2.rt,trials.thisRepN,trials.thisTrialN,trials.thisN,trials.thisIndex,trials.ran,trials.order,participant,session,date,expName,psychopyVersion,frameRate
> 0.18220339,-0.286723164,1,0,0,2.496,"[""left"",""right""]","[2.016,2.183]",5,0,5,0,1,4,,001,2019-02-25_16h11.39.818,mouseTesting,3.0.4,60
> 0.18220339,-0.286723164,1,0,0,3.198,"[""y"",""n"",""space"",""left"",""right""]","[1.7640000000000002,2.0310000000000006,2.2640000000000002,2.697,2.931]",5,0,5,0,1,4,,001,2019-02-25_16h11.39.818,mouseTesting,3.0.4,60
> 0.18220339,-0.286723164,1,0,0,1.63,"[""y"",""n""]","[1.1949999999999994,1.412]",5,0,5,0,1,4,,001,2019-02-25_16h11.39.818,mouseTesting,3.0.4,60
> 0.18220339,-0.286723164,1,0,0,1.465,"[""left""]",[1.064],5,0,5,0,1,4,,001,2019-02-25_16h11.39.818,mouseTesting,3.0.4,60
> 0.18220339,-0.286723164,1,0,0,1.311,"[""right""]",[0.9440000000000008],5,0,5,0,1,4,,001,2019-02-25_16h11.39.818,mouseTesting,3.0.4,60

Let me know what you think!

Alain

**Comment by peircej** [comment]
Yes, we had to do the same thing from Python, and the format above looks the same as ours

**Comment by apitiot** [comment]
Super!
I'm closing the issue, then.

**Comment by dvbridges** [comment]
Great, thanks. I was just attempting to test this, but came across a merge conflict so was just sorting that out.
