### ISSUE TITLE
BUG: slider.setFillColor is not a function

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychojs#322]
no option to set the fill color of markers using a variable. Minimal bug here. 
https://gitlab.pavlovia.org/lpxrh6/markerfill-bug-demo

**Comment by thewhodidthis** [comment]
Thanks for flagging @RebeccaHirst, I'm looking at this as part of #315 as well. Please is fill the highlight or the background color in say a radio box type slider?
