### ISSUE TITLE
slider local/online incompatibilities in reference to markers

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychojs#323]
Marker position for sliders is referenced as `slider.markerPos` locally but `slider._markerPos` online. Since users use this attribute to change things dynamically using sliders these need to marry up for easy use.

**Comment by RebeccaHirst** [comment]
Note that this could resolve the issue because attributes will be accessed with same method used locally https://github.com/psychopy/psychojs/pull/324

**Comment by thewhodidthis** [comment]
Hi @RebeccaHirst, I could be missing something, but [it looks like](https://run.pavlovia.org/thewhodidthis/slider/) both `slider.markerPos` and `slider.getMarkerPos()` work as described.

**Comment by RebeccaHirst** [comment]
Roger that just checked, looks fine, must have been a mistake - sorry Sotiri!
