### ISSUE TITLE
Pop out of Full Screen

### ISSUE THREAD

**Issue by pntfx4** [psychopy/psychojs#33]
The builder generated script stays in full screen display mode after quitPsychoJS requiring the user to exit full screen mode manually. I can see the advantage of this, but by default it should return the user to their normal display settings which are likely not full screen.

This could be done by fixing the builder translation to either add "document.exitFullscreen();" to quitPsychoJS, or to modify quitPsychoJS to take a boolean parameter to return full screen.

**Comment by peircej** [comment]
Agreed. This makes sense. Is it something that can be detected before we go full-screen (if a user was full-screen before starting the study we don't want to exit that state for them)?

**Comment by apitiot** [comment]
Thank you for the suggestion!
I am now automatically detecting the state of the browser's window (fullscreen or not) at the start of the experiment, and bringing the window back to that state at the end of it.
You can test this approach in [demos/stroop](https://run.pavlovia.org/demos/stroop/html).
