### ISSUE TITLE
Users reporting "mismatched states for OAuth2 authentication, possible CSRF attack?" error

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#36]
Today, a user reported the following error:

{ “origin”: “pavlovia.org”, “context”: “when signing in”, “error”: “mismatched states for OAuth2 authentication, possible CSRF attack?”}

On my home Linux box, I also received this error today. So, not specific to one computer, as I had previously thought.

**Comment by apitiot** [comment]
I have made changes to the way OauthStates are used, which should correct this (somewhat rare) issue.
I took that opportunity to make sure that users are systematically redirected back to pavlovia.org/explore after they sign-out.
