### ISSUE TITLE
Video component doesn't present

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#367]
In 2021.2.0, a video component does not present correctly; instead a strange string of bytes triggers an error message.
* [example of issue](https://staging.psychopy.org/experiments/issue_demos/wdio_video/)
* [corresponding experiment](https://github.com/psychopy/psychojs_testing/tree/main/tests/wdio_video)

**Comment by tpronk** [comment]
This issue seems mostly fixed,, except that the video doesn't play on iOS. There I get the error message below.
![image](https://user-images.githubusercontent.com/8987504/121919555-079fc400-cd2f-11eb-892c-bfbcd8d23678.png)

For an example experiment, see: 
* Deployed: https://staging.psychopy.org/experiments/demo_for_sotiri/wdio_video/
* Raw psyexp: https://github.com/psychopy/psychojs_testing/tree/main/tests/wdio_video

**Comment by thewhodidthis** [comment]
@tpronk Sorry, the issue here seems to be with some of the #368 changes you suggested, see #397

**Comment by tpronk** [comment]
Aha. What did you find out?

**Comment by tpronk** [comment]
I don't think the issue is #368. I added some further comments on this in #397. Instead, I've made an alternative fork that keeps your bug-fix, but does feature the `data-error` logging, which is very handy for our automated testing. Before we merge it though, I'd like to check it with @apitiot
