### ISSUE TITLE
TrialHandler does not support nReps or random/sequential method

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#4]
As far as I can see we can't currently run more than one cycle of a set of conditions. 

The code to select `TrialHandler.thisTrial` is commented out at 
https://github.com/psychopy/psychojs/blob/65667d241e8fac4c2aca92d2a0f538fb6eda0c48/js/psychojs/data.js#L163-L172

In the test examples we've indexed into the conditions file entries directly (i.e. not using the TrialHandler to do this)

**Comment by jonathanoroberts** [comment]
I believe I'm very close to finishing some code to fix this issue for nReps and sequential/random/fullRandom... It involves changes to data.js in psychoJS and minor changes to the exporting of the index.html file in psychoPy. Once I have tested it a bit more, is the next step submitting pull requests to both repositories with the same commit message?

**Comment by peircej** [comment]
OK, great! Yes, this needs a pull request to each project I think - to be honest git sub-projects are new to me and it's _conceivable_ that a commit to the parent project (psychopy) will automatically cause a commit to the child (psychojs)

**Comment by peircej** [comment]
fixed in #10
