### ISSUE TITLE
Should we add "Variable Components" to PsychoJS?

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#419]
I'm examining what it would take to make the [pizza-calculator](https://gitlab.pavlovia.org/demos/pizza-calculator) run on PsychoJS. It uses "Variable Components" , but we don't support those yet. Should we add them?

**Comment by peircej** [comment]
I don't believe this needs adding in PsychoJS - it's a pure boilerplate thing

**Comment by tpronk** [comment]
Thnx @peircej! Shall I close this one and file an issue for PsychoPy?

**Comment by peircej** [comment]
I think so. It's purely about creating a variable, updating it and saving it at the right time. There's a question about whether it's useful at all but if it exists there's no reason for it not to have a JS buddy

**Comment by tpronk** [comment]
Wow, GitHub is aware of the link I made to this post! Closing this issue now...
