### ISSUE TITLE
Removed resources are still present and downloaded

### ISSUE THREAD

**Issue by kastman** [psychopy/psychojs#42]
Problem: I added a bunch of images to the wrong directory manually in `html/resources`. I then moved them and `git rm`'d them, so that they're now not in the current git tree. However, they are still being listed and found by resource loader and downloaded at the start of the task each time, which is doubling startup time for some already embarrassingly large images. 

I suspect the pavlovia server is downloading a zip of the task and unzipping it to overwrite things instead of checking out a repo, and that the resource list is just built by listing the directory? I'm sure there's a way to reset this (maybe even a new fork of the repo), but it seems like something that would be helpful to fix.

Also, a feature request would be to not display the _name_ of each resource in the loading dialogue but only show the progress, as the names of stimuli or other resources can sometimes have meaning that you wouldn't want a participant to see. If that sounds reasonable I'll add it as another issue.

**Comment by peircej** [comment]
The run area of pavlovia is actually git pulling from the repo so this _shouldn't_ be happening. I wonder if your stimuli are cached somewhere.

I agree about the filenames and added issue #43

**Comment by kastman** [comment]
Wasn't able to duplicate this on a fresh repo; closing it for now.
