### ISSUE TITLE
error when using waitForResources() function: ReferenceError: Clock is not defined

### ISSUE THREAD

**Issue by hahahannes** [psychopy/psychojs#425]
When I try to use `ServerManager.waitForResources`, I get a `ReferenceError` with the message Clock is not defined which comes from line https://github.com/psychopy/psychojs/blob/main/src/core/ServerManager.js#L540.
I guess this is caused by a missing import statement at https://github.com/psychopy/psychojs/blob/main/src/core/ServerManager.js#L15.

Version: 2021.2.0

**Comment by thewhodidthis** [comment]
@hahahannes Good catch, thanks for flagging
