### ISSUE TITLE
Button: Button component does not end routine and doesn't save data

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychojs#439]
Currently clicking a button doesn't force the end of that routine (even though force end routine is selected) and (maybe as a consequence?) data are not saved to the output file from button components 

Minimal demo here: https://run.pavlovia.org/lpxrh6/n_back_basic_2/

**Comment by thewhodidthis** [comment]
Thanks for flagging @RebeccaHirst, this looks like a boilerplate issue

**Comment by RebeccaHirst** [comment]
I think this is now fixed in the current release? I just tried and could no longer replicate. If you agree we an close this issue?
