### ISSUE TITLE
PsychoJS loop not breaking

### ISSUE THREAD

**Issue by nadiaBRS** [psychopy/psychojs#440]
Hi, 

I have a problem with my online PsychoPy experiment. Here is my setup: participants read some instructions, and then undergo a training during which they have to answer 8 questions. I set a nested loop and a treshold that send them back to the beginning of the training if they perform less than 60% (around 5/8 questions). It works fine locally, but when I take it online, we get stuck in the loop. So even if the participant have 8/8, the training starts again. I tried modifying the JS script manually, and replace the last bit to trials.finished=true; (also tried <loop>.finished = true; and currentLoop.finished = true;), as suggested in other discussions, but nothing works. Any ideas ?

![Capture d’écran 2021-07-22 à 15 34 53](https://user-images.githubusercontent.com/87816089/126647967-155973c8-4584-422a-b5b4-bd85409b07bd.png)
![Capture d’écran 2021-07-22 à 15 34 58](https://user-images.githubusercontent.com/87816089/126647969-7bfdb8bb-9043-4971-acf0-273b4e333762.png)

**Comment by thewhodidthis** [comment]
Hi @nadiaBRS, thanks for flagging, this looks boilerplate related. Would it be possible to follow up on PsychoPy's discourse forum? It would be really helpful for me to be able to look at your project in full so I can debug properly, x

**Comment by nadiaBRS** [comment]
Ok so after many trials, here is the solution:

![Capture d’écran 2021-08-04 à 12 01 57](https://user-images.githubusercontent.com/87816089/128162603-1d849f68-7689-4972-8a43-1e0c73017f50.png)

In the CtrlTrainGo routine, add a code component. In the “begin routine” tab, add a counter: number_correct = 0

In the CtrlTrial routine, in the “end routine” tab of the code component, do this:
if CtrlTrainAns.corr:
number_correct += 1
if number_correct >= 5:
ctrl_training_outer.finished = True

That’s it ! Hope it will help someone in the future.
