### ISSUE TITLE
Reference Error: letterColor not defined, running Stroop on local server

### ISSUE THREAD

**Issue by Ashwani270292** [psychopy/psychojs#459]
I wish to host an experiment on local server, documentation says psychopy should be running on the server. I am a newbie and doesnot have much context of how to host it.

This has been done.

now getting error in getting reference from .xls file in resources.
Please see code snippet and error.

function trialRoutineBegin(trials) {
	return function () {
		//------Prepare to start Routine 'trial'-------
		t = 0;
		trialClock.reset(); // clock
		frameN = -1;
		// update component parameters for each repeat
		word.setColor(new util.Color(letterColor));
		word.setText(text);
		resp.keys = undefined;
		resp.rt = undefined;
		// keep track of which components have finished
		trialComponents = [];
		trialComponents.push(word);
		trialComponents.push(resp);

		for (const thisComponent of trialComponents)
			if ('status' in thisComponent)
				thisComponent.status = PsychoJS.Status.NOT_STARTED;

		return Scheduler.Event.NEXT;
	};
	
 Error:
 Uncaught ReferenceError: letterColor is not defined
    at Scheduler._currentTask (stroop.js:300)
    at Scheduler._runNextTasks (util-2020.2.js:1570)
    at Scheduler._runNextTasks (util-2020.2.js:1574)
    at Scheduler._runNextTasks (util-2020.2.js:1574)
    at update (util-2020.2.js:1527)

while the xls contains letterColor column

**Comment by thewhodidthis** [comment]
Hi @Ashwani270292, thanks for flagging. Were you able to resolve this? To better address the issue, would it be possible to please start a new topic including a link to your study on [PsychoPy's forum](http://discourse.psychopy.org)?

**Comment by peircej** [comment]
@Ashwani270292 we don't support installation on your own hosting unless you have a site license and need it because of institutional policies, in which case we can help you install a Pavlovia satellite server. That isn't to say it's not possible, but we don't support it
