### ISSUE TITLE
TrialHandler attributes are not updated after creation

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#49]
TrialHandler attributes (e.g., below) need to update every block and every trial:
```
.thisRepN - which repeat you are currently on
.thisTrialN - which trial number within that repeat
```
In PsychoPy, this happens within the trialhandler class (see \_\_next__  iterator method).

https://github.com/psychopy/psychopy/blob/2dfefd7506ea3f7b4854454b61210dcc7586928e/psychopy/data/trial.py#L316

**Comment by apitiot** [comment]
That is rather surprising. Could you provide me with a sample experiment?

**Comment by dvbridges** [comment]
Thanks for looking Alain, here is an example. The text components have the trialHandler attributes set to update on every repeat, or every trial. 

https://pavlovia.org/run/dvbridges/trialattributes/html/

**Comment by robpetrosino** [comment]
Hi, would it be at all possible to have some update on the issue? 

Thanks!

**Comment by apitiot** [comment]
Hello Roberto and David,

What you are experiencing has to do with the fact that PsychoJs experiments are entirely scheduled **before** they start running. That means that the internal variables of a TrialHandler, such as nTotal, will not change at run time, they only change at scheduling time.
I did not originally intend them to be available during running but it certainly is possible to capture their values during the scheduling in a way to make them accessable at runtime. For the sake of convenience, I've just added the method TrialHandler.getSnapshot, which returns an object with various internal variables:

```
getSnapshot() {
	return {
		nStim: this.nStim,
		nTotal: this.nTotal,
		nRemaining: this.nRemaining,
		thisRepN: this.thisRepN,
		thisTrialN: this.thisTrialN,
		thisN: this.thisN,
		thisIndex: this.thisIndex
	};
}
```

 It can be used as follows:

- In trialsLoopBegin, we capture a snapshot and pass it to trialRoutineBegin

```
  // Schedule all the trials in the trialList:
  for (const thisTrial of trials) {
    thisScheduler.add(importConditions(trials));
    thisScheduler.add(trialRoutineBegin(trials.getSnapshot()));
    thisScheduler.add(trialRoutineEachFrame);
    thisScheduler.add(trialRoutineEnd);
    thisScheduler.add(endLoopIteration(thisScheduler, thisTrial));
  }
```

- trialRoutineBegin now returns a function:

```
function trialRoutineBegin(trials) {
	return function () {
		[...]
		// update component parameters for each repeat
		trialNTotal.setText(('nTotal: ' + trials.nTotal));
		trialnRemaining.setText(('nRemaining: ' + trials.nRemaining));
		trialN.setText(('thisN: ' + trials.thisN));
		trialRepN.setText(('thisRepN: ' + trials.thisRepN));
		trialTrialN.setText(('thisTrialN: ' + trials.thisTrialN));
		[...]
		return Scheduler.Event.NEXT;
	}
}
```

This ensures that the repeated calls to trialRoutineBegin in the trialsLoopBegin function will all contain a different snapshot of trials.

I hope this helps! Let me know what you think.
Cheers,


Alain

**Comment by robpetrosino** [comment]
Hi Alain,
thank you for your message. I am no JS expert, so forgive my naive question. What I am trying to implement in my experiment is a break after a given number of trials has been presented. In particular, a trial consists of a number of routines as shown in the Flow figure below: the routines `fmaskWarm`, `primeWarm` and `targetWarm are to be presented one after the other in the loop `loopWarm` and the routine `breakWarm` should be presented after, say, half of the fmask-prime-target triplets have been presented.

![Screen Shot 2019-04-23 at 9 03 18 PM](https://user-images.githubusercontent.com/30778296/56976160-4dde3d00-6b40-11e9-8ccc-dcce5e2d5682.png)

If I understand correctly, you are suggesting to insert the line

`thisScheduler.add(trialRoutineBegin(trials.getSnapshot()));`

at the beginning of the loop (i.e., when importing the conditions for that loop). This way, I could refer to the `trialHandler` attributes in the `breakWarm` routine for my purposes.

Is that correct?

**Comment by robpetrosino** [comment]
UPDATE: I tried to follow your instructions, and the following message pops up:

![Screen Shot 2019-05-01 at 8 28 21 AM](https://user-images.githubusercontent.com/30778296/57016993-1a0c2180-6beb-11e9-90b7-05684fa42fbc.png)

URL to the experiment: [https://pavlovia.org/run/roberto.petrosino/maskedpriming/html/](url)

**Comment by apitiot** [comment]
Let me have a look. I should be able to get back to you later today or tomorrow at the latest.

**Comment by robpetrosino** [comment]
UPDATE. Now no error pops up, but the counter does not seem to update properly. Here's an except of my code.

`var loopWarm;
var currentLoop;
function loopWarmLoopBegin(thisScheduler) {
  // set up handler to look after randomisation of conditions etc
  loopWarm = new TrialHandler({
    psychoJS: psychoJS,
    nReps: 1, method: TrialHandler.Method.RANDOM,
    extraInfo: expInfo, originPath: undefined,
    trialList: 'warm_up.csv',
    seed: undefined, name: 'loopWarm'});
  psychoJS.experiment.addLoop(loopWarm); // add the loop to the experiment
  currentLoop = loopWarm;  // we're now the current loop

  // Schedule all the trials in the trialList:
  for (const thisLoopWarm of loopWarm) {
    thisScheduler.add(importConditions(loopWarm));
    thisScheduler.add(fmaskWarmRoutineBegin(loopWarm.getSnapshot()));
    //thisScheduler.add(fmaskWarmRoutineBegin);
    thisScheduler.add(fmaskWarmRoutineEachFrame);
    thisScheduler.add(fmaskWarmRoutineEnd);
    thisScheduler.add(primeWarmRoutineBegin);
    thisScheduler.add(primeWarmRoutineEachFrame);
    thisScheduler.add(primeWarmRoutineEnd);
    thisScheduler.add(targetWarmRoutineBegin);
    thisScheduler.add(targetWarmRoutineEachFrame);
    thisScheduler.add(targetWarmRoutineEnd);
    thisScheduler.add(breakWarmRoutineBegin);
    thisScheduler.add(breakWarmRoutineEachFrame);
    thisScheduler.add(breakWarmRoutineEnd);
    thisScheduler.add(endLoopIteration(thisScheduler, thisLoopWarm));
  }

  return Scheduler.Event.NEXT;
}

[...]

function breakWarmRoutineBegin() {
  //------Prepare to start Routine 'breakWarm'-------
  t = 0;
  breakWarmClock.reset(); // clock
  frameN = -1;
  // update component parameters for each repeat
  if ( loopWarm.thisTrialN !== (loopWarm.nTotal/2) ) {     
      continueRoutine === false; 
  } //take a break after first half of stimuli has been presented
  
  text_breakWarm.text = "You can now take a short break.\n\nThere are " + (loopWarm.nRemaining+1) + " words left. \nthisN="+loopWarm.thisN+"\nthisTrialN:"+loopWarm.thisTrialN+"\nnTotal:"+loopWarm.nTotal+"\n\nWhen you are ready, press 'SPACE' to resume the experiment.";
  key_breakWarm = new core.BuilderKeyResponse(psychoJS);
  
  // keep track of which components have finished
  breakWarmComponents = [];
  breakWarmComponents.push(key_breakWarm);
  breakWarmComponents.push(text_breakWarm);
  
  for (const thisComponent of breakWarmComponents)
    if ('status' in thisComponent)
      thisComponent.status = PsychoJS.Status.NOT_STARTED;
  
  return Scheduler.Event.NEXT;
}

`

**Comment by apitiot** [comment]
You were almost there. You have to alter breakWarmRoutineBegin so it take loopWarm as a parameter and returns a function, as per my example above.
I have made the changes to your experiment on the repository: you'll see them if you pull.
Cheers,

Alain

**Comment by robpetrosino** [comment]
Thank you, Alain! I can see that now the counter works, though the `breakWarm` routine still shows up at every trial instead of after half of the stimuli are presented. Is there any issue with the if-statement I wrote (ll. 763-4 of my code)?

**Comment by apitiot** [comment]
My pleasure!
I'll leave you in the hands of David for the if-statement issue.
@dvbridges would you mind having a quick look?

Alain

**Comment by dvbridges** [comment]
Thanks @apitiot , adding this to the JS output. @robpetrosino , the if-statement is not working because you are testing the `continueRoutine` variable for equality with `false`, rather than assigning the value of `continueRoutine` as false. Try:

```javascript
if ( loopWarm.thisTrialN !== (loopWarm.nTotal/2) ) {     
      continueRoutine = false; 
  } //take a break after first half of stimuli has been presented
```

**Comment by robpetrosino** [comment]
@dvbridges, thank you for replying so quickly. I just tried that but the `breakWarm` routine still pops up at every trial. I am not sure if that is the right place to discuss this - I am sorry if that is not the case. We could continue the discussion on the forum.

**Comment by apitiot** [comment]
Yes, if you don't mind, do continue independently from this particular thread.

@dvbridges I'll contact you next week to discuss changes to the code generation related to systematically getting snapshots and passing them to all routines.
