### ISSUE TITLE
questions about psychojs

### ISSUE THREAD

**Issue by teonbrooks** [psychopy/psychojs#5]
Hey, cool project. I have two questions:

1) what license does your package use? I see in the LICENSE it says BSD but the files themselves mention GPL-3
2) I was wondering what your motivation is for using php instead of nodejs

I am currently working on combining two projects ([openexp](https://github.com/openscilab/openexp) and [expfactory](https://github.com/expfactory/expfactory) that would work to support deploying experiments in an electron app or web page powered by different backends such as jspsych or perhaps soon psychojs.

**Comment by peircej** [comment]
Hi Teon

1. we anticipate it having the 3-clause BSD. The files have just recently been moved out of the PsychoPy library which uses GPL3+, but I don't think that's needed here.
2. the design decision around php versus node.js was made by Ilixa and I'll leave it to them (it might not be set in stone)

cheers,
Jon

**Comment by xxxspy** [comment]
why not use python like tornado as the server?

**Comment by peircej** [comment]
The choice of web server is up to the scientist at present (anything that supports PHP)

**Comment by teonbrooks** [comment]
cool, thanks for the clarification @peircej
