### ISSUE TITLE
Triangle marker in Slider does not scale 

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#50]
The size of the triangle marker is not scaling the with vertical dimension of the Slider, and as a result looks too big

[_Example Slider_](https://pavlovia.org/run/dvbridges/slidertriangle/html/)

**Comment by apitiot** [comment]
The triangular markers are indeed scaling with the vertical dimension of the Slider. They were however too big, by a factor of 2.
I have made the change in version 3.1.5 (and the future 3.2.0).
I'm closing the issue.

Alain
