### ISSUE TITLE
FILE_LOAD_ERROR for some participants whilst experiment loading

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#54]
A user has the occasional participant receiving  a FILE_LOAD_ERROR while completing the personal info field during the experiment resource download stage.

The error reported [on Discourse](https://discourse.psychopy.org/t/file-load-error/7895) was found on Windows machine using Chrome - No further info given.

_URL to the task_
https://gitlab.pavlovia.org/AndreiRazvanCostea/edsc30

**Comment by apitiot** [comment]
I believe the recent substantial changes to the Pavlovia back-end have resolved that problem, whatever that was. The matter has been discussed with Andrei, who has confirmed that his experiment was now running fine.

I'm closing the issue.
