### ISSUE TITLE
PsychoJS versions

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#56]
Github isn't up to date with pavlovia version of psychojs:
- no changes pushed to github since 3.0.8 (now 3.1.1)
- no changes pulled from github e.g. commit fb8115c68e756b

We also need to add version 3.1.2 release version to pavlovia/lib

**Comment by apitiot** [comment]
3.0.8 was the last version before the substantial rewrite to Pavlovia backend and GUI. I have been testing the new version extensively: it should be ready to push in the coming days.
