### ISSUE TITLE
setup with own webserver

### ISSUE THREAD

**Issue by hageldave** [psychopy/psychojs#585]
The documentation is lacking details on how to run a study online **without hosting on pavlovia.org**.
There could be GDPR related limitations on where or how to host an experiment and it would be helpful to know how to setup the experiment with a standard webserver such as [Apache](https://httpd.apache.org/).

Are there any server side scripts that need to be executed, any databases to be setup? How will the server receive the data collected in the experiment?

**Comment by fuimsr** [comment]
Had the same problem and solved it by using [JATOS](https://www.jatos.org).

I don't want to get into the argument if this is better, more secure, less expensive or whatever, as it has been discussed here: https://discourse.psychopy.org/t/psychopy-to-jatos/14334/3


Our solution:
We've removed the automatic download function from psychojs-2023.2.2.js and added a send_to_JATOS function to each experiment. Pretty easy and straight forward once we established a routine.





Add to the experiment.js file:
```
async function quitPsychoJS(message, isCompleted) {
  // Check for and save orphaned data
  if (psychoJS.experiment.isEntryEmpty()) {
    psychoJS.experiment.nextEntry();
  }

  jatos.endStudy(psychoJS.experiment._trialsData) //<-- ADD THIS LINE HERE TO YOUR EXPORTED EXPERIMENT.js

  psychoJS.window.close();
  psychoJS.quit({message: message, isCompleted: isCompleted});
  
  return Scheduler.Event.QUIT;
}
```

Remove from psychojs-2023.1.2.js:
![grafik](https://github.com/psychopy/psychojs/assets/141765018/b2ad50a5-66ba-418f-96a5-c00040391a9f)

**Comment by peircej** [comment]
Certainly there are ways for highly technical users to create their own solutions, as noted above, but they aren't something we're going to spend time supporting, for the various reasons (efficiency of effort, weaker security, as well as our need to maintain a sustainable dev team for the project).
