### ISSUE TITLE
Add .editorconfig file to PsychoJS repository

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#59]
Lets add a `.editorconfig` file to the PsychoJS repository so we have consistent indentation for the HTML and JS files, see [EditorConfig](https://editorconfig.org/). Currently, the indentation in JS and HTML looks wrong because of GitHubs default settings (I think is 8 spaces for an indent?). Setting a `.editorconfig` file allows us to define what indentation params should be used for specific file types. Below is all that is required...

```
# top-most EditorConfig file
root = true

# Don't use tabs for indentation.
[*]
indent_style = space
# (Please don't specify an indent_size here; that has too many unintended consequences.)

# Python files
[*.{py}]
indent_style = tab
indent_size = 4

# HTML+CSS/JS  files
[*.{html,css,js}]
indent_style = tab
indent_size = 2
```

**Comment by peircej** [comment]
That sounds good Dave. I'd say go ahead and submit a PR with that

**Comment by apitiot** [comment]
I've merged the PR.
I'm closing the issue.
