### ISSUE TITLE
TextStim.pos is 200?

### ISSUE THREAD

**Issue by xxxspy** [psychopy/psychojs#6]
I write a little demo to test the TextStim and failed. The code : 
-----
```    <script type='text/javascript'>
      // wait until document is ready:
      $(document).ready(function() {{
        psychoJS.frameCount=0;
        win= new psychoJS.visual.Window({color:'green', size:(300,300)});
        psychoJS.init(win);
        s=new psychoJS.Scheduler();
        t = new psychoJS.visual.TextStim({text:'hello wold', 'win':win,pos:(100,200), color: 'red'})
        t2=new PIXI.Text('hello world 2');
        task=function(){
            t.draw();
            // t.pixiRep.position={x:1,y:2}
            
            win._container.addChild(t2);
            console.log(win._container.children.length)
            // win._renderer.render(win._container);
            return

            console.log(psychoJS.frameCount);
            if( psychoJS.frameCount<500)return psychoJS.FLIP_REPEAT;
        }
        s.add(task);
        s.start(win);
        // s.run()
    }})</script>
```

-------------
No error but the `t` did not show while `t2` is right. 
And in the console , `t._pos` is 200 . Why? I missed anything?

**Comment by peircej** [comment]
Maybe it has the wrong units? position in PsychoPy/JS can have different units than pixels

**Comment by xxxspy** [comment]
oh , i checked my code. the `pos=(100,200)` should be `pos=[100,200]`, I am a pythoner. But  the `t` not show up stil.

**Comment by peircej** [comment]
Well, the way to debug this is gradually make the code closer the one that works. Try that and see where it "breaks".
Honestly though I think you might need to look into the concept of different units. If your stimulus units are "norm" then your image is drawing 100 times to the right of the screen and 200 times higher than the screen so will not be visible

**Comment by xxxspy** [comment]
A lot Thanks! Now `t` is right there.
