### ISSUE TITLE
When setting ImageStim.image=None don't crash but don't draw

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#61]
Users often set an image to be absent in their conditions file but leaving the cell blank. The result is a call to `stim.setImage(undefined)` but that currently raises an error. What we need is for that not to raise an error but when it comes to rendering the image simply draw nothing

**Comment by apitiot** [comment]
I have just pushed a fix for 3.1.4 and 3.1.5. We now get a warning instead of an error, so the experiment continues running.
