### ISSUE TITLE
Error parsing config.json maybe caused by unicode project name?

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#63]
You can see the issue here:
https://run.pavlovia.org/demos/muller-lyer-illusion/html/

My best guess about what's different here is that the user called it Müller-Lyer Illusion (with the umlaut) and maybe the config file using that name instead of the GitLab ASCII name in the file?

```
Unfortunately we encountered an error:

    when starting the experiment
    when configuring PsychoJS for the experiment
    when reading the configuration file: config.json
    SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Try to run the experiment again. If the error persists, contact the experiment designer.
```

**Comment by apitiot** [comment]
Good guess! As with the Spanish inquisition, nobody expects the umlaut ;-)

I've updated the server back-end and corrected a couple of issues with the experiment itself (missing and incorrectly referenced resources): it's running like a charm.
I'm closing the issue.

Alain
