### ISSUE TITLE
We should permit ImageStim image=undefined and TextStim.text=undefined

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#66]
Currently setting the contents of the Image or text to undefined result in an error, but it's very useful for users to set this to mean "no stimulus". We need the stimulus to receive those happily and then jst not perform a draw() operation when image=undefined

![image](https://user-images.githubusercontent.com/380582/62302359-1bf7b200-b472-11e9-97d2-14f8ad9a6712.png)

**Comment by apitiot** [comment]
This is the case and has been applied retro-actively all the way back to 3.0.7.
I'm closing the issue.
