### ISSUE TITLE
On Mac Safari there's an 'invalid key' beep on any keypress in the study

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#67]
I think this is consistent for all studies.

**Comment by peircej** [comment]
This was fixed

**Comment by etidoni** [comment]
I am experiencing the same issue.
Only when the script is run online.
That is, using psychopy no problem, running my codes or running others' codes using Pavlova an invalid key sound is generated at each keypress.

**Comment by peircej** [comment]
Is this on Safari? Could you confirm thte version of PsychoPy being used?
thanks,

**Comment by etidoni** [comment]
Safari Version 13.0.5 (15608.5.11)
PsychPy version 2020.1

**Comment by naomileenaomi** [comment]
Same issue as of today! Runs fine (with no noise) in Chrome, but Safari plays funk.caf for every keypress:
- on Safari (Version 11.1.1 (13605.2.8))
- developed in PsychoPy standalone v2020.1.2
- run on Pavlovia PsychoJS Version 2020.1
