### ISSUE TITLE
Adjustments to text alignment in PsychoJS

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#74]
Text in PsychoJS is currently centered and has spacing between paragraphs whereas in PsychoPy 3.2 it's left-aligned and no paragraph spacing. In PsychoPy now we're getting the option to choose

**Comment by peircej** [comment]
https://discourse.psychopy.org/t/cannot-left-align-text-in-javascript/7052

**Comment by thewhodidthis** [comment]
I believe 2020.1 Text stimuli are [left-aligned by default](https://github.com/psychopy/psychojs/blob/master/js/visual/TextStim.js#L62) @peircej, safe to close?

**Comment by tpronk** [comment]
A word of warning; in the newest PsychoJS I indeed get left-aligned text, but in PsychoPy 2020.2.0dev1 it's still center aligned.

Example: https://gitlab.pavlovia.org/tpronk/e2e_conditions

**Comment by thewhodidthis** [comment]
@tpronk @peircej I am looking at addressing anchoring related issues mentioned on above forum thread as part of #70
