### ISSUE TITLE
PsychoJS slider marker only shows up on release

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#75]
In PsychoPy the markerPos is given a value as soon as the mouse button goes down and, at that point, it causes the marker to be drawn to the screen (so it then follows the mouse being dragged). On release the rating value is then set and marked as a response occuring. 

Reports are that on psychojs the marker doesn't appear until the mouse button is released. Maybe this is a difference in logic, of maybe it's a difference in the way the event works?

https://discourse.psychopy.org/t/slider-marker-not-visible-online/8668/3

**Comment by apitiot** [comment]
I have now fixed the issue. The fix is available for versions 3.2, 3.2.0, 3.2.5, 2020.1, and 2020.2.
