### ISSUE TITLE
Running Psychojs in local server.

### ISSUE THREAD

**Issue by iPsych** [psychopy/psychojs#79]
Dear all, 
Due to I have to significantly modify PsychoPy code itself (i.e. change lines in Keyboard, which disabled some 'normal' function of it to get special kind of input like non-alphabetic strings),
I am trying to run Psychojs in local server.
It worked properly till I face to '/api/v2/experiments/'.
The text stimuli without images can be run properly with specifying 'conditions.xlsx' as resource in starting point as below.

```
psychoJS.start({
	expName,
	expInfo,
	resources: [
		{ name: 'conditions.xlsx', path: 'resources/conditions.xls' }
	]
});
```

**Issue 01** **However, it cannot load the images inside the excel file, in same 'resources' folder.** 
In the code, it seems to run some 'server-side' scripts in pavlovia.org/api/v2/experiments/.

**Issue 02** **The result of experiment is correct, but 'downloaded' to participant's computer** 

Is there any possibility to resolve this?

**Comment by peircej** [comment]
Running PsychoJS experiments from your own servers isn't something we're directly supporting, at least in the near future. You can edit code and still upload to Pavlovia though (indeed you can use labjs and jsPsych experiments on pavlovia too.

**Comment by Ashwani270292** [comment]
Hi,
Have we received any update on this issue, I wish to run psychojs on a local server, and then host my experiments locally for some internal studies in a school.
I have been trying to figure out a way but not having any luck.

**Comment by Ashwani270292** [comment]
Documentation says, Psychojs library should be live on server, how this can be achieved?

**Comment by NiRo-2** [comment]
what i did to run PsychoJs on local server is to compile the source, take the compiled dlls and create the loca lib dir.
if anyone want, this is a ready to use offline template.
https://drive.google.com/file/d/14ysYfOXg17Z9nNeUi-hS6XW0DnAsf-dD/view?usp=sharing
