### ISSUE TITLE
Multiple mouse components in a trial causes syntax error

### ISSUE THREAD

**Issue by jfkominsky** [psychopy/psychojs#88]
I discovered this from this thread: https://discourse.psychopy.org/t/initialising-experiment/13220

In short, if you create a trial that has multiple "mouse" components (not that I'm sure there's really a reason to do this), when that trial ends, "const xys" is declared for _each_ mouse, leading to a syntax error. While there's no real reason to have multiple mouse components, the nature of this issue is opaque to the user, and will either need a safeguard in the builder or a trick for making all mouse components refer to the same xys variable.

**Comment by thewhodidthis** [comment]
@TEParsons Just adding a couple of Mouse components without touching any settings, this is the JS I end up with. Would it be possible to have the second `xys` variable named something like eg. `xys_2`? Is there an option for that in PsychoPy already?

```js
function trialRoutineEnd(snapshot) {
  return function () {
    //------Ending Routine 'trial'-------
    for (const thisComponent of trialComponents) {
      if (typeof thisComponent.setAutoDraw === 'function') {
        thisComponent.setAutoDraw(false);
      }
    }
    // store data for thisExp (ExperimentHandler)
    const xys = mouse.getPos();
    const buttons = mouse.getPressed();
    psychoJS.experiment.addData('mouse.x', xys[0]);
    psychoJS.experiment.addData('mouse.y', xys[1]);
    psychoJS.experiment.addData('mouse.leftButton', buttons[0]);
    psychoJS.experiment.addData('mouse.midButton', buttons[1]);
    psychoJS.experiment.addData('mouse.rightButton', buttons[2]);
    // store data for thisExp (ExperimentHandler)
    const xys = mouse_2.getPos();
    const buttons = mouse_2.getPressed();
    psychoJS.experiment.addData('mouse_2.x', xys[0]);
    psychoJS.experiment.addData('mouse_2.y', xys[1]);
    psychoJS.experiment.addData('mouse_2.leftButton', buttons[0]);
    psychoJS.experiment.addData('mouse_2.midButton', buttons[1]);
    psychoJS.experiment.addData('mouse_2.rightButton', buttons[2]);
    return Scheduler.Event.NEXT;
  };
}
```

**Comment by TEParsons** [comment]
Ah I see, is this not allowed in JS? We could cut out the middleman and just use `mouse​.​getPos​(​)` in the calls to `addData`

**Comment by thewhodidthis** [comment]
That would be one call to `getPos()` extra if I understand you correctly, but would certainly avoid the problem. Please note, declaring the `buttons` variable twice causes the same kind of error.

**Comment by TEParsons** [comment]
Would it work if we just used `let` rather than `const`? I don't have the contextual knowledge of JavaScript to fully know what the difference is but from the looks of [this](https://www.w3schools.com/js/js_const.asp) it seems like `let` is the same but it won't crash if we assign it a different value later?

**Comment by jfkominsky** [comment]
I did a little testing in the w3schools tryit environment and it looks like consecutive `let` calls within the same block generates the same error as consecutive `const` calls. You can declare the variable with `let` and then change its value, e.g.

```
let x = 5;
x = 6;
```
which you couldn't do with `const`, but you can't declare the same variable with `let` twice within the same block, so in terms of how mouse components work, it doesn't solve the problem.

**Comment by thewhodidthis** [comment]
Yes I see what you mean, you should be able to use the old `var` for that

**Comment by jfkominsky** [comment]
The problem with `var` is that it doesn't have block scope, which is why `let` and `const` exist at all. The risk is that the xys variable could then be references from outside the block, or potentially carry over between trials. However, because it's a function, I'm not sure that's actually what would happen, but I assume there was a reason to use `const` rather than `var` in the first place.

**Comment by thewhodidthis** [comment]
Good point, we should aim for a long term solution like tweaking the variable naming scheme rather than a temporary workaround like using `var`

**Comment by peircej** [comment]
In general we *do* allow variables to be used outside their blocks, despite the dangers, because:
- that's what happens in the equivalent Python script
- it's less confusing to novice users than having to explain the concept of scopes 
- they'll only be able to see what the scopes are by compiling the script

So a very simple fix, as @thewhodidthis suggests would be to give this a global scope with var at the top of the script like all the other variables

**Comment by thewhodidthis** [comment]
Closing in light of psychopy/psychopy#3122

**Comment by thewhodidthis** [comment]
Closing in light of psychopy/psychopy#3122
