### ISSUE TITLE
"Is trials" flag has no effect online

### ISSUE THREAD

**Issue by wakecarter** [psychopy/psychojs#91]
I have an experiment which loads the stimuli into arrays in loops before the main trials loop. Locally I suppress these loops from the data file by de-selecting "Is trials". However, online I am still getting the extra rows.

Please see [https://discourse.psychopy.org/t/is-trials-switch-doesn-t-work-online/13510](https://discourse.psychopy.org/t/is-trials-switch-doesn-t-work-online/13510) for more details including sample data files.

Best wishes,

Wakefield

**Comment by thewhodidthis** [comment]
@peircej As discussed earlier, it looks like this can be handled on the PsychoPy end of things. I've removed the issue from the project board, but I leave open for further comments if need be.
