### ISSUE TITLE
How to import psychojs into my project?

### ISSUE THREAD

**Issue by Yiyue15** [psychopy/psychojs#92]
Hi, 

Sorry if this is not a place where I should be posting this... 

I've currently converted the python code into javascript. However, it seems that I require Psychojs to my project. Do you have anything inside your `README.md` file which beginner could use as a starting point?

Thanks a lot!

**Comment by sou-chon** [comment]
It depends whether you are using a javascript bundler (and which one) for your code or writing a script that is directly loaded onto the browser.

For the former case, if, for example, you are using [Webpack](https://webpack.js.org/), you can download this repo and use the [import syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

For the later case, you can use the import syntax if using newer browsers, or bring Psychojs in scope like this:
`<script type="application/javascript" src="https://lib.pavlovia.org/core-3.2.js"></script>`

**Comment by Yiyue15** [comment]
Hi Sou-Chon,

Thanks so much for the very kind help! I can successfully import the package!

However, I've encountered this error:`TypeError: Cannot read property 'logger' of undefined
    at HTMLDocument.<anonymous>` at line 1508 `self._psychoJS.logger.trace('keydown: ', event.key);`

Do you happen to have any idea? Also, please feel free to let me know if this is not an appropriate place to ask this type of question and I'll close the issue accordingly

**Comment by Yiyue15** [comment]
Thanks so much Sou-Chon!! Yes that resolved my issue :) 
I'll mark this issue as closed then
